/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPollCreator,
  IPollCreatorInterface,
} from "../../DAOHistory.sol/IPollCreator";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "daoId",
        type: "string",
      },
      {
        internalType: "string",
        name: "projectId",
        type: "string",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "createPoll",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPollCreator__factory {
  static readonly abi = _abi;
  static createInterface(): IPollCreatorInterface {
    return new utils.Interface(_abi) as IPollCreatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPollCreator {
    return new Contract(address, _abi, signerOrProvider) as IPollCreator;
  }
}
