/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type VoteStruct = {
  voter: PromiseOrValue<string>;
  candidates: PromiseOrValue<string>[];
  points: PromiseOrValue<BigNumberish>[][];
  comments: PromiseOrValue<string>[];
  perspectiveId: PromiseOrValue<BigNumberish>;
};

export type VoteStructOutput = [
  string,
  string[],
  BigNumber[][],
  string[],
  BigNumber
] & {
  voter: string;
  candidates: string[];
  points: BigNumber[][];
  comments: string[];
  perspectiveId: BigNumber;
};

export type ContributionItemStruct = {
  contributionText: PromiseOrValue<string>;
  evidences: PromiseOrValue<string>[];
  roles: PromiseOrValue<string>[];
  contributor: PromiseOrValue<string>;
  pollId: PromiseOrValue<BigNumberish>;
};

export type ContributionItemStructOutput = [
  string,
  string[],
  string[],
  string,
  BigNumber
] & {
  contributionText: string;
  evidences: string[];
  roles: string[];
  contributor: string;
  pollId: BigNumber;
};

export type DetailPollItemStruct = {
  pollId: PromiseOrValue<BigNumberish>;
  contributions: ContributionItemStruct[];
  voters: PromiseOrValue<string>[];
  startTimeStamp: PromiseOrValue<BigNumberish>;
  endTimeStamp: PromiseOrValue<BigNumberish>;
  perspectives: PromiseOrValue<string>[];
};

export type DetailPollItemStructOutput = [
  BigNumber,
  ContributionItemStructOutput[],
  string[],
  BigNumber,
  BigNumber,
  string[]
] & {
  pollId: BigNumber;
  contributions: ContributionItemStructOutput[];
  voters: string[];
  startTimeStamp: BigNumber;
  endTimeStamp: BigNumber;
  perspectives: string[];
};

export interface PollInterface extends utils.Interface {
  functions: {
    "COMMISION_RATE()": FunctionFragment;
    "CONTRIBUTOR_ASSIGNMENT_TOKEN()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "VOTER_ASSIGNMENT_TOKEN()": FunctionFragment;
    "VOTE_MAX_PARTICIPANT()": FunctionFragment;
    "activePerspective()": FunctionFragment;
    "candidateToCurrentPoll(string,string[],string[])": FunctionFragment;
    "changePerspective(string[])": FunctionFragment;
    "commisionAddress()": FunctionFragment;
    "currentMaxPollId()": FunctionFragment;
    "daoTokenAddress()": FunctionFragment;
    "endTimeStamp(int256)": FunctionFragment;
    "getCommisionToken()": FunctionFragment;
    "getCurrentCandidates()": FunctionFragment;
    "getCurrentPerspectives()": FunctionFragment;
    "getCurrentVotes()": FunctionFragment;
    "getPerspectives(uint256)": FunctionFragment;
    "getPollDetail(int256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getVoters(int256)": FunctionFragment;
    "getVotes(int256)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isEligibleToVote(address)": FunctionFragment;
    "nftAddress()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setAssignmentToken(uint256,uint256)": FunctionFragment;
    "setDaoHistoryAddress(address)": FunctionFragment;
    "setPollAdminRole(address)": FunctionFragment;
    "setTokenAddress(address,address)": FunctionFragment;
    "setVoteMaxParticipant(uint256)": FunctionFragment;
    "setVotingDuration(int256,uint256)": FunctionFragment;
    "settleCurrentPollAndCreateNewPoll()": FunctionFragment;
    "startTimeStamp(int256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vote(int256,address[],uint256[][],string[])": FunctionFragment;
    "votingDuration()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "COMMISION_RATE"
      | "CONTRIBUTOR_ASSIGNMENT_TOKEN"
      | "DEFAULT_ADMIN_ROLE"
      | "VOTER_ASSIGNMENT_TOKEN"
      | "VOTE_MAX_PARTICIPANT"
      | "activePerspective"
      | "candidateToCurrentPoll"
      | "changePerspective"
      | "commisionAddress"
      | "currentMaxPollId"
      | "daoTokenAddress"
      | "endTimeStamp"
      | "getCommisionToken"
      | "getCurrentCandidates"
      | "getCurrentPerspectives"
      | "getCurrentVotes"
      | "getPerspectives"
      | "getPollDetail"
      | "getRoleAdmin"
      | "getVoters"
      | "getVotes"
      | "grantRole"
      | "hasRole"
      | "isEligibleToVote"
      | "nftAddress"
      | "owner"
      | "renounceOwnership"
      | "renounceRole"
      | "revokeRole"
      | "setAssignmentToken"
      | "setDaoHistoryAddress"
      | "setPollAdminRole"
      | "setTokenAddress"
      | "setVoteMaxParticipant"
      | "setVotingDuration"
      | "settleCurrentPollAndCreateNewPoll"
      | "startTimeStamp"
      | "supportsInterface"
      | "transferOwnership"
      | "vote"
      | "votingDuration"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "COMMISION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONTRIBUTOR_ASSIGNMENT_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTER_ASSIGNMENT_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VOTE_MAX_PARTICIPANT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activePerspective",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "candidateToCurrentPoll",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changePerspective",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "commisionAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentMaxPollId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "daoTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "endTimeStamp",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommisionToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentCandidates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPerspectives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPerspectives",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPollDetail",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoters",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligibleToVote",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssignmentToken",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoHistoryAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPollAdminRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenAddress",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoteMaxParticipant",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingDuration",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "settleCurrentPollAndCreateNewPoll",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startTimeStamp",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[][],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "votingDuration",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COMMISION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONTRIBUTOR_ASSIGNMENT_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTER_ASSIGNMENT_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VOTE_MAX_PARTICIPANT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activePerspective",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "candidateToCurrentPoll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changePerspective",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commisionAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentMaxPollId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "daoTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "endTimeStamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommisionToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentCandidates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPerspectives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPerspectives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPollDetail",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVoters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEligibleToVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nftAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssignmentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoHistoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPollAdminRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVoteMaxParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleCurrentPollAndCreateNewPoll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startTimeStamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingDuration",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
}

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface Poll extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PollInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    COMMISION_RATE(overrides?: CallOverrides): Promise<[BigNumber]>;

    CONTRIBUTOR_ASSIGNMENT_TOKEN(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    VOTER_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<[BigNumber]>;

    VOTE_MAX_PARTICIPANT(overrides?: CallOverrides): Promise<[BigNumber]>;

    activePerspective(overrides?: CallOverrides): Promise<[BigNumber]>;

    candidateToCurrentPoll(
      contributionText: PromiseOrValue<string>,
      evidences: PromiseOrValue<string>[],
      roles: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changePerspective(
      perspectiveTexts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    commisionAddress(overrides?: CallOverrides): Promise<[string]>;

    currentMaxPollId(overrides?: CallOverrides): Promise<[BigNumber]>;

    daoTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    endTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCommisionToken(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentCandidates(overrides?: CallOverrides): Promise<[string[]]>;

    getCurrentPerspectives(overrides?: CallOverrides): Promise<[string[]]>;

    getCurrentVotes(overrides?: CallOverrides): Promise<[VoteStructOutput[]]>;

    getPerspectives(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getPollDetail(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[DetailPollItemStructOutput]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getVoters(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getVotes(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[VoteStructOutput[]]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isEligibleToVote(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nftAddress(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAssignmentToken(
      _contributorToken: PromiseOrValue<BigNumberish>,
      _voterToken: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDaoHistoryAddress(
      _daoHistoryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPollAdminRole(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTokenAddress(
      _daoTokenAddress: PromiseOrValue<string>,
      _nftAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setVoteMaxParticipant(
      _voteMaxParticipant: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setVotingDuration(
      pollId: PromiseOrValue<BigNumberish>,
      _votingDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    settleCurrentPollAndCreateNewPoll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vote(
      _pollId: PromiseOrValue<BigNumberish>,
      _candidates: PromiseOrValue<string>[],
      _points: PromiseOrValue<BigNumberish>[][],
      _comments: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    votingDuration(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  COMMISION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

  CONTRIBUTOR_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  VOTER_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

  VOTE_MAX_PARTICIPANT(overrides?: CallOverrides): Promise<BigNumber>;

  activePerspective(overrides?: CallOverrides): Promise<BigNumber>;

  candidateToCurrentPoll(
    contributionText: PromiseOrValue<string>,
    evidences: PromiseOrValue<string>[],
    roles: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changePerspective(
    perspectiveTexts: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  commisionAddress(overrides?: CallOverrides): Promise<string>;

  currentMaxPollId(overrides?: CallOverrides): Promise<BigNumber>;

  daoTokenAddress(overrides?: CallOverrides): Promise<string>;

  endTimeStamp(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCommisionToken(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentCandidates(overrides?: CallOverrides): Promise<string[]>;

  getCurrentPerspectives(overrides?: CallOverrides): Promise<string[]>;

  getCurrentVotes(overrides?: CallOverrides): Promise<VoteStructOutput[]>;

  getPerspectives(
    _pollId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getPollDetail(
    _pollId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<DetailPollItemStructOutput>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getVoters(
    _pollId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getVotes(
    _pollId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<VoteStructOutput[]>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isEligibleToVote(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nftAddress(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAssignmentToken(
    _contributorToken: PromiseOrValue<BigNumberish>,
    _voterToken: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDaoHistoryAddress(
    _daoHistoryAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPollAdminRole(
    _address: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTokenAddress(
    _daoTokenAddress: PromiseOrValue<string>,
    _nftAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setVoteMaxParticipant(
    _voteMaxParticipant: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setVotingDuration(
    pollId: PromiseOrValue<BigNumberish>,
    _votingDuration: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  settleCurrentPollAndCreateNewPoll(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startTimeStamp(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vote(
    _pollId: PromiseOrValue<BigNumberish>,
    _candidates: PromiseOrValue<string>[],
    _points: PromiseOrValue<BigNumberish>[][],
    _comments: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  votingDuration(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    COMMISION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    CONTRIBUTOR_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    VOTER_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    VOTE_MAX_PARTICIPANT(overrides?: CallOverrides): Promise<BigNumber>;

    activePerspective(overrides?: CallOverrides): Promise<BigNumber>;

    candidateToCurrentPoll(
      contributionText: PromiseOrValue<string>,
      evidences: PromiseOrValue<string>[],
      roles: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    changePerspective(
      perspectiveTexts: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    commisionAddress(overrides?: CallOverrides): Promise<string>;

    currentMaxPollId(overrides?: CallOverrides): Promise<BigNumber>;

    daoTokenAddress(overrides?: CallOverrides): Promise<string>;

    endTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCommisionToken(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentCandidates(overrides?: CallOverrides): Promise<string[]>;

    getCurrentPerspectives(overrides?: CallOverrides): Promise<string[]>;

    getCurrentVotes(overrides?: CallOverrides): Promise<VoteStructOutput[]>;

    getPerspectives(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getPollDetail(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<DetailPollItemStructOutput>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getVoters(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getVotes(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<VoteStructOutput[]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isEligibleToVote(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nftAddress(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAssignmentToken(
      _contributorToken: PromiseOrValue<BigNumberish>,
      _voterToken: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDaoHistoryAddress(
      _daoHistoryAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPollAdminRole(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenAddress(
      _daoTokenAddress: PromiseOrValue<string>,
      _nftAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setVoteMaxParticipant(
      _voteMaxParticipant: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setVotingDuration(
      pollId: PromiseOrValue<BigNumberish>,
      _votingDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    settleCurrentPollAndCreateNewPoll(overrides?: CallOverrides): Promise<void>;

    startTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vote(
      _pollId: PromiseOrValue<BigNumberish>,
      _candidates: PromiseOrValue<string>[],
      _points: PromiseOrValue<BigNumberish>[][],
      _comments: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    votingDuration(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
  };

  estimateGas: {
    COMMISION_RATE(overrides?: CallOverrides): Promise<BigNumber>;

    CONTRIBUTOR_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    VOTER_ASSIGNMENT_TOKEN(overrides?: CallOverrides): Promise<BigNumber>;

    VOTE_MAX_PARTICIPANT(overrides?: CallOverrides): Promise<BigNumber>;

    activePerspective(overrides?: CallOverrides): Promise<BigNumber>;

    candidateToCurrentPoll(
      contributionText: PromiseOrValue<string>,
      evidences: PromiseOrValue<string>[],
      roles: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changePerspective(
      perspectiveTexts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    commisionAddress(overrides?: CallOverrides): Promise<BigNumber>;

    currentMaxPollId(overrides?: CallOverrides): Promise<BigNumber>;

    daoTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    endTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCommisionToken(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentCandidates(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPerspectives(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentVotes(overrides?: CallOverrides): Promise<BigNumber>;

    getPerspectives(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPollDetail(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVoters(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotes(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isEligibleToVote(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nftAddress(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAssignmentToken(
      _contributorToken: PromiseOrValue<BigNumberish>,
      _voterToken: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDaoHistoryAddress(
      _daoHistoryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPollAdminRole(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTokenAddress(
      _daoTokenAddress: PromiseOrValue<string>,
      _nftAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setVoteMaxParticipant(
      _voteMaxParticipant: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setVotingDuration(
      pollId: PromiseOrValue<BigNumberish>,
      _votingDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    settleCurrentPollAndCreateNewPoll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vote(
      _pollId: PromiseOrValue<BigNumberish>,
      _candidates: PromiseOrValue<string>[],
      _points: PromiseOrValue<BigNumberish>[][],
      _comments: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    votingDuration(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    COMMISION_RATE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    CONTRIBUTOR_ASSIGNMENT_TOKEN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VOTER_ASSIGNMENT_TOKEN(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    VOTE_MAX_PARTICIPANT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    activePerspective(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    candidateToCurrentPoll(
      contributionText: PromiseOrValue<string>,
      evidences: PromiseOrValue<string>[],
      roles: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changePerspective(
      perspectiveTexts: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    commisionAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    currentMaxPollId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    daoTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    endTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCommisionToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentCandidates(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentPerspectives(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCurrentVotes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPerspectives(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPollDetail(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVoters(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVotes(
      _pollId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isEligibleToVote(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nftAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAssignmentToken(
      _contributorToken: PromiseOrValue<BigNumberish>,
      _voterToken: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDaoHistoryAddress(
      _daoHistoryAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPollAdminRole(
      _address: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTokenAddress(
      _daoTokenAddress: PromiseOrValue<string>,
      _nftAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setVoteMaxParticipant(
      _voteMaxParticipant: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setVotingDuration(
      pollId: PromiseOrValue<BigNumberish>,
      _votingDuration: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    settleCurrentPollAndCreateNewPoll(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startTimeStamp(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vote(
      _pollId: PromiseOrValue<BigNumberish>,
      _candidates: PromiseOrValue<string>[],
      _points: PromiseOrValue<BigNumberish>[][],
      _comments: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    votingDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
